"""empty message

Revision ID: 04a97c2ed788
Revises: c5ed3de4d900
Create Date: 2023-01-26 19:00:40.405190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a97c2ed788'
down_revision = 'c5ed3de4d900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kills', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deaths', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('deaths')
        batch_op.drop_column('kills')

    # ### end Alembic commands ###
