"""empty message

Revision ID: 8954bcd1875c
Revises: c836d37f3e12
Create Date: 2023-01-27 19:48:41.105858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8954bcd1875c'
down_revision = 'c836d37f3e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('front_shiny_sprite',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('front_shiny_sprite',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
