"""empty message

Revision ID: c836d37f3e12
Revises: cea1f92a3ef3
Create Date: 2023-01-27 17:41:23.396653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c836d37f3e12'
down_revision = 'cea1f92a3ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('front_shiny_sprite',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('front_shiny_sprite',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
