"""empty message

Revision ID: cea1f92a3ef3
Revises: 04a97c2ed788
Create Date: 2023-01-27 17:12:52.651984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea1f92a3ef3'
down_revision = '04a97c2ed788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_column('base_experience')
        batch_op.drop_column('ability_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ability_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('base_experience', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
